_BASE_: "Base-DiffusionDet.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  DiffusionDet:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (350, 420) # 350000, 420000 => 350, 420
  MAX_ITER: 450 # 450000=> 450
>>>>>>> ff1cc2375ec71402c3ccc414d95d77a09c096907
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
